### ISSUE TITLE
Message[AddInputAlias::badnb, "rxn",   AddInputAlias[NotationTemplateTag[\[Placeholder]  \!\(\*OverscriptBox[\(\[RightArrow]\), \(\(\ \)\(\[Placeholder]\)\(\ \ \)\)]\) \[Placeholder] ], "rxn"]]; $Failed

### ISSUE THREAD

**Issue by dbl001** [marko-vasic/crnPlusPlus#2]
I am getting this error running the example code on Mathematica 13.

The second argument of AddInputAlias is not a notebook object.

<img width="2560" alt="Screen Shot 2022-02-27 at 11 22 35 AM" src="https://user-images.githubusercontent.com/3105499/155896706-46e2a5c0-b712-473c-a4c2-7972a86219ce.png">

<img width="2560" alt="Screen Shot 2022-02-27 at 11 22 35 AM" src="https://user-images.githubusercontent.com/3105499/155896618-d8eac90b-e6b5-4825-8283-24dc1cb8333e.png">

**Comment by marko-vasic** [comment]
Thanks for the feedback!
I suppose this is some issue introduced by a new version of Mathematica.
I will investigate this and let you know.
In either case, the output looks good -- plot is what is expected to be.

**Comment by marko-vasic** [comment]
I updated the CRNSimulator.m package which resolves the issue.
